In [2]:
import numpy as np

In [10]:
x=np.array([1,2,3,4,5])
N=len(x)

In [11]:
matrix=np.column_stack([x**(N-i-1) for i in range(N)])
print(matrix)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [13]:
mat=np.vander(x,N)
print(mat)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [23]:

#nums=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
#k=3
#n=len(nums)
#sum=0
#for i in range(n-k+1):
    #for i in range(k):
        #sum=sum+nums[i]
        #avg=sum/k
    #print(avg)

In [22]:
def mov_avg(arr,k):
    sums=np.cumsum(arr,dtype=float)
    sums[k:]=sums[k:]-sums[:-k]
    return sums[k-1:]/k
arr=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k=3
n=len(arr)
np.array(mov_avg(arr,k)).round(2)

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])